apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: cosmosworkload
spec:
  image: "ghcr.io/squillace/cosmosworkload:0.1.3"
  executor: containerd-shim-spin
  replicas: 2
  runtimeConfig:
    loadFromSecret: cosmosworkload-runtime-config
  podLabels:
    azure.workload.identity/use: "true" 
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmosworkload-runtime-config
type: Opaque
data:
  runtime-config.toml: W2tleV92YWx1ZV9zdG9yZS5kZWZhdWx0XQp0eXBlID0gImF6dXJlX2Nvc21vcyIgICAgCmFjY291bnQgPSAiY29zbW9zLXNwaW4iICAgIApkYXRhYmFzZSA9ICJzcGluIiAgICAKY29udGFpbmVyID0gImtleXMtYW5kLXZhbHVlcyIgICAgCmVudmlyb25tZW50YWwtYXV0aCA9ICJ0cnVlIg==
