[key_value_store.default]
type = "azure_cosmos"    
account = "spin-kv-cosmos-db"    
database = "spin"    
container = "keys-and-values"    
# key = "client id, or remove this entirely for managed workload support" 