apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: cosmosworkload
spec:
  image: "ghcr.io/squillace/cosmosworkload:0.1.0"
  executor: containerd-shim-spin
  replicas: 2
  runtimeConfig:
    loadFromSecret: cosmosworkload-runtime-config
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmosworkload-runtime-config
type: Opaque
data:
  runtime-config.toml: W2tleV92YWx1ZV9zdG9yZS5kZWZhdWx0XQp0eXBlID0gImF6dXJlX2Nvc21vcyIgICAgCmFjY291bnQgPSAic3Bpbi1rdi1jb3Ntb3MtZGIiICAgIApkYXRhYmFzZSA9ICJzcGluIiAgICAKY29udGFpbmVyID0gImtleXMtYW5kLXZhbHVlcyIgICAgCiMga2V5ID0gImNsaWVudCBpZCwgb3IgcmVtb3ZlIHRoaXMgZW50aXJlbHkgZm9yIG1hbmFnZWQgd29ya2xvYWQgc3VwcG9ydCIg
