apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin-test
        azure.workload.identity/use: "true"
    spec:
      automountServiceAccountToken: true
      # runtimeClassName: wasmtime-spin-v2
      volumes:
        - name: spin-runtime-config
          secret:
            secretName: cosmosworkload-runtime-config      
      containers:
        - name: spin-kv
          env:
          - name: RUST_LOG
            value: spin=trace
          - name: SPIN_RUNTIME_CONFIG_FILE
            value: /var/cosmos-keyvalue-config.toml
          volumeMounts:
            # name must match the volume name above
            - name: spin-runtime-config
              mountPath: "/var"
              readOnly: true      
         # NOTE: here we are using a spin CONTAINER with a spin application inside
         # so we know that the env var is correct and populated correctly. Note that the args are different.
          image: ghcr.io/fermyon/spin:v3.0.0
          command: ["/usr/local/bin/spin"]
          args:
            - "up"
            - "-f"
            - "ghcr.io/squillace/cosmosworkload:0.1.0"
            - "--runtime-config-file"
            - "/var/cosmos-keyvalue-config.toml"
          imagePullPolicy: IfNotPresent

          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: workload-identity
      serviceAccountName: workload-identity
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmosworkload-runtime-config
type: Opaque
data:
  cosmos-keyvalue-config.toml: W2tleV92YWx1ZV9zdG9yZS5kZWZhdWx0XQp0eXBlID0gImF6dXJlX2Nvc21vcyIgICAgCmFjY291bnQgPSAic3Bpbi1rdi1jb3Ntb3MtZGIiICAgIApkYXRhYmFzZSA9ICJzcGluIiAgICAKY29udGFpbmVyID0gImtleXMtYW5kLXZhbHVlcyIgICAgCiMga2V5ID0gImNsaWVudCBpZCwgb3IgcmVtb3ZlIHRoaXMgZW50aXJlbHkgZm9yIG1hbmFnZWQgd29ya2xvYWQgc3VwcG9ydCIg
