apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin-test
        azure.workload.identity/use: "true"
    spec:
      automountServiceAccountToken: true
      runtimeClassName: wasmtime-spin
      containers:
      - env:
        - name: RUST_LOG
          value: debug
        image: ghcr.io/squillace/cosmosworkload:latest
        command: ["/"]
        imagePullPolicy: IfNotPresent
        name: spin-kv
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: workload-identity
      serviceAccountName: workload-identity
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
