spin_manifest_version = 2

[application]
authors = ["ralph squillace <ralph@squillace.com>"]
description = ""
name = "cosmosworkload"
version = "0.1.0"

[[trigger.http]]
route = "/kv"
component = "cosmosworkload"

[component.cosmosworkload]
source = "target/cosmosworkload.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://spin-kv-cosmos-db.documents.azure.com:443/"]
key_value_stores = ["default"]


[component.cosmosworkload.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]